################################################################################
# PromptForge Docker Swarm Stack Configuration
################################################################################
#
# This stack configuration provides container orchestration with:
#   - Service scaling
#   - Rolling updates
#   - Health checks and auto-restart
#   - Load balancing (built-in swarm routing mesh)
#   - Service constraints and placement
#
# Usage:
#   docker stack deploy -c ha/swarm/docker-stack.yml promptforge
#
################################################################################

version: '3.8'

services:
  #-----------------------------------------------------------------------------
  # PostgreSQL Primary
  #-----------------------------------------------------------------------------
  postgres-primary:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-promptforge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-promptforge_prod}
      POSTGRES_REPLICATION_USER: ${POSTGRES_REPLICATION_USER:-replicator}
      POSTGRES_REPLICATION_PASSWORD: ${POSTGRES_REPLICATION_PASSWORD}
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - /opt/promptforge/ha/postgresql/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - /opt/promptforge/ha/postgresql/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - /opt/promptforge/ha/postgresql/init:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-promptforge}"]
      interval: 10s
      timeout: 5s
      retries: 5

  #-----------------------------------------------------------------------------
  # Redis Master
  #-----------------------------------------------------------------------------
  redis-master:
    image: redis:7-alpine
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - redis_master_data:/data
    ports:
      - "6379:6379"
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  #-----------------------------------------------------------------------------
  # Redis Sentinels
  #-----------------------------------------------------------------------------
  redis-sentinel:
    image: redis:7-alpine
    command: redis-sentinel /etc/redis/sentinel.conf
    configs:
      - source: redis_sentinel_config
        target: /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
    depends_on:
      - redis-master

  #-----------------------------------------------------------------------------
  # Backend Application
  #-----------------------------------------------------------------------------
  backend:
    image: ${DOCKER_REGISTRY:-localhost:5000}/promptforge-backend:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-promptforge}:${POSTGRES_PASSWORD}@postgres-primary:5432/${POSTGRES_DB:-promptforge_prod}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis-master:6379/0
      SECRET_KEY: ${SECRET_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      WORKERS: ${BACKEND_WORKERS:-2}
      ENVIRONMENT: production
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  #-----------------------------------------------------------------------------
  # Frontend Application
  #-----------------------------------------------------------------------------
  frontend:
    image: ${DOCKER_REGISTRY:-localhost:5000}/promptforge-frontend:latest
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  #-----------------------------------------------------------------------------
  # Nginx Load Balancer
  #-----------------------------------------------------------------------------
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_lb_config
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: ssl_cert
        target: /etc/nginx/ssl/cert.pem
      - source: ssl_key
        target: /etc/nginx/ssl/key.pem
    networks:
      - promptforge_network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - backend
      - frontend

#-----------------------------------------------------------------------------
# Networks
#-----------------------------------------------------------------------------
networks:
  promptforge_network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.9.0/24

#-----------------------------------------------------------------------------
# Volumes
#-----------------------------------------------------------------------------
volumes:
  postgres_primary_data:
    driver: local
  redis_master_data:
    driver: local

#-----------------------------------------------------------------------------
# Configs (for non-sensitive configuration)
#-----------------------------------------------------------------------------
configs:
  nginx_config:
    file: ../../nginx/nginx.conf
  nginx_lb_config:
    file: ../nginx/load-balancer.conf
  redis_sentinel_config:
    file: ../redis/sentinel.conf

#-----------------------------------------------------------------------------
# Secrets (for sensitive data)
#-----------------------------------------------------------------------------
secrets:
  ssl_cert:
    file: ../../nginx/ssl/cert.pem
  ssl_key:
    file: ../../nginx/ssl/key.pem

################################################################################
# Docker Swarm Stack Notes
################################################################################
#
# Deployment:
#   docker stack deploy -c ha/swarm/docker-stack.yml promptforge
#
# Scaling:
#   docker service scale promptforge_backend=5
#   docker service scale promptforge_frontend=3
#
# Updates:
#   docker service update --image new-image:tag promptforge_backend
#
# Rollback:
#   docker service rollback promptforge_backend
#
# Monitoring:
#   docker stack ps promptforge
#   docker service ls
#   docker service logs promptforge_backend
#
# Remove:
#   docker stack rm promptforge
#
################################################################################
